[tool.poetry]
name = "aiohttp-boilerplate"
version = "0.1.11"
description = ""
authors = ["Vladyslav Tarasenko <vladka@webdevelop.pro>"]
license = "MIT"

[tool.poetry.dependencies]
aiohttp = "=3.6.2"
asyncpg = "=0.20.1"
marshmallow = "=2.19.5"
ujson = "=1.35"
uvloop = "=0.14.0"
PyJWT = "=1.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
